app/basket/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *
from django.views.generic import TemplateView
from app.basket import views

from app.basket.views import AddToBasket, RemoveOneFromBasket, RemoveFromBasket, OrderView, SetCountBasket, \
    AddToBasketJSON, RemoveFromBasketJSON, RemoveOneFromBasketJSON, GetDelivery

urlpatterns = patterns('',
    ###==оформление заказа==###
    #Список товаров корзины
    #url(r'^$', Index, name = 'basket-index'),

    #форма заказа
    url(r'^order/$', OrderView.as_view(), name = 'basket-order'),

    #Окончательное завершение заказа
    url(r'^success/$', TemplateView.as_view(template_name='basket/success.html'), name = 'basket-success'),

    #Удаление товара из корзины
    url(r'^remove/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', RemoveFromBasket.as_view(), name = 'basket-remove'),
    url(r'^remove-json/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', RemoveFromBasketJSON.as_view(), name = 'basket-remove-json'),

    #Удаление одного товара из корзины
    url(r'^remove-one/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', RemoveOneFromBasket.as_view(), name = 'basket-remove-one'),
    url(r'^remove-one-json/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', RemoveOneFromBasketJSON.as_view(), name = 'basket-remove-one-json'),

    url(r'^add/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', AddToBasket.as_view(), name='basket-add'),
    url(r'^add-json/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', AddToBasketJSON.as_view(), name='basket-add-json'),

    url(r'^set-count/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', SetCountBasket.as_view(), name='basket-set-count'),


    url(r'^get-delivery/$', GetDelivery.as_view(), name = 'basket-get-delivery'),

)

sport/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap

from filebrowser.sites import site
from xendor.models import Page
from app.article.models import Article
from app.catalog.models import Category, Product

admin.autodiscover()

category_dict = {
    'queryset': Category.objects.filter(visible=True),
}

product_dict = {
    'queryset': Product.objects.filter(visible=True),
}

article_dict = {
    'queryset': Article.objects.all(),
}

pages_dict = {
    'queryset': Page.objects.filter(visible=True, app_extension='', in_menu=True),
}

sitemaps = {
    'products': GenericSitemap(product_dict, priority=0.8),
    'category': GenericSitemap(category_dict, priority=0.9),
    'article': GenericSitemap(article_dict, priority=0.9),
    'pages': GenericSitemap(pages_dict, priority=0.6),
}

urlpatterns = patterns('',

    url(r'^captcha/(?P<code>[\da-f]{32})/$', 'app.supercaptcha.draw'),

    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    (r'^tinymce/', include('tinymce.urls')),

    url(r'^admin/filebrowser/', include(site.urls)),

    (r'^grappelli/', include('grappelli.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^contacts/', include('app.contacts.urls')),

    url(r'^callback/', include('app.callback.urls')),

    url(r'^news/', include('app.news.urls')),

    url(r'^article/', include('app.article.urls')),

    url(r'^response/', include('app.response.urls')),

    url(r'^basket/', include('app.basket.urls')),

    url(r'^', include('app.catalog.urls')),

    # XDP-page
    url(r'^page/', include('xendor.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

app/basket/models.py
# -*- coding: utf-8 -*-
from django.contrib.contenttypes import generic
from django.db import models
from django.contrib.contenttypes.models import ContentType


class OrderedItem(models.Model):
    """Заказанный объект"""

    #Привязка к контент-тайп фреймворку
    content_type = models.ForeignKey(ContentType, verbose_name=u'Тип контента', related_name="content_type_set_for_%(class)s")
    object_pk = models.IntegerField('ID объекта')
    content_object = generic.GenericForeignKey(ct_field="content_type", fk_field="object_pk")

    #На случай будущих изменений цены
    price = models.DecimalField(u'Цена на момент заказа', max_digits=19, decimal_places=2, null=True, blank=True)
    count = models.IntegerField(u'Количество', default=1)
    order = models.ForeignKey('Order', verbose_name=u'Заказ')

    class Meta:
        verbose_name = u'заказанный объект'
        verbose_name_plural = u'Заказанные объекты'

    def __unicode__(self):
        return unicode(self.content_type.get_object_for_this_type(pk=self.object_pk).name)

    def get_total_price(self):
        return self.count * self.price


class Delivery(models.Model):
    """Справочник доставки"""

    name = models.CharField(u'Название', max_length=255)
    price = models.DecimalField(u'Стоимость', max_digits=19, decimal_places=2, default=0, help_text=u'Фиксированная сумма в рублях')

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = u'Справочник доставки'
        verbose_name_plural = u'Справочник доставки'


class Payment(models.Model):
    """Способ оплаты"""
    name = models.CharField(u'Название', max_length=255)
    price = models.IntegerField(u'Стоимость %', default=0, help_text=u'Стоимость доставки в процентах')

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = u'Способ оплаты'
        verbose_name_plural = u'Способ оплаты'


class OrderStatus(models.Model):
    """Статусы заказа"""

    name = models.CharField(u'Название статуса', max_length=255)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = u'статус'
        verbose_name_plural = u'Статусы'


class Order(models.Model):
    """Заказы с сайта"""

    created = models.DateTimeField(u'Дата оформления заказа', auto_now_add=True)
    price = models.DecimalField(u'Сумма заказа', max_digits=19, decimal_places=2, null=True, blank=True)

    delivery = models.ForeignKey(Delivery, verbose_name=u'Доставка', null=True, blank=True)
    payment = models.ForeignKey(Payment, verbose_name=u'Способ оплаты', null=True, blank=True)
    person = models.CharField(u'Ваше имя', max_length=255, null=True, blank=True)
    phone = models.CharField(u'Ваш номер телефона', max_length=255)
    mail = models.EmailField(u'Почта', max_length=255, blank=True, null=True)
    address = models.TextField(u'Адрес доставки', blank=True, null=True)
    comment = models.TextField(u'Комментарий', blank=True, null=True)
    eula = models.BooleanField(u'Подтверждение ознакомления с пользовательским соглашением', default=False)

    status = models.ForeignKey(OrderStatus, verbose_name=u'Статус заказа', null=True, blank=True)
    order_comment = models.TextField(u'Комментарий менеджера', blank=True, null=True)

    def __unicode__(self):
        return str(self.created)

    class Meta:
        ordering = u'-created',
        verbose_name = u'заказ с сайта'
        verbose_name_plural = u'Заказы с сайта'

app/basket/views.py
# -*- coding: utf-8 -*-
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import get_current_site
from django.core.mail import EmailMessage
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe
from django.views.generic import CreateView, TemplateView, RedirectView
from xendor.cbv import RefererRedirectWithMessage, ContentTypeMixin, ToStructureMixin, JSONResponseMixin, WithMailer

from xendor.settings import XendorSettings
from xendor.templatetags.utils import _formater_1000
from app.basket import clean_basket
from app.basket.forms import OrderForm
from app.basket.models import Order, OrderedItem, Delivery, Payment


def _recalculate_basket_price(basket):
    """Пересчет суммарной цены, планируемые скидки и прочую фигню подключать здесь"""

    # ContentType.objects.get_for_id().get_object_for_this_type(pk=pk)

    return sum([ContentType.
                objects.
                get_for_id(basket[x]['content_type_id']).
                get_object_for_this_type(pk=basket[x]['object_id']).
                get_price() * basket[x]['count']
                for x in basket.keys() if x not in ('price', 'payment', 'delivery')])


def _get_basket_items(basket):
    """получение списка товаров лежащих в корзине"""

    return [(ContentType.
                      objects.
                      get_for_id(basket[x]['content_type_id']).
                      get_object_for_this_type(pk=basket[x]['object_id']), basket[x]['count'])
                      for x in basket.keys() if x not in ('price', 'payment', 'delivery')]


class OrderView(WithMailer, CreateView):
    """Заказ товаров"""

    model = Order
    form_class = OrderForm
    template_name = 'basket/order.html'

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)
        basket = self.request.session.get('basket', {})
        context.update({
            'items': _get_basket_items(basket),
            'price': basket.get('price', 0),
            'count': len([y for x, y in basket.items() if not x in ('price',)]),
        })
        return context

    def get_success_url(self):
        return reverse('basket-success')

    def form_valid(self, form):
        basket = self.request.session.get('basket', {})

        price = float(basket.get('price', 0))
        delivery_price = 0
        payment_price = 0
        try:
            delivery_price = form.cleaned_data.get('delivery').price
        except:
            pass

        try:
            payment_price = form.cleaned_data.get('payment').price
        except:
            pass

        price = float(price) + float(delivery_price)
        price = price + (float(payment_price) * price/100)

        self.object = form.save()
        self.object.price = price

        items = _get_basket_items(basket)

        for item in items:
            ordered_item = OrderedItem(
                content_object=item[0],
                price=item[0].price,
                count=item[1],
                order=self.object
            )
            ordered_item.save()

            clean_basket(self.request)

        self.send_mail(
            'Новая покупка на сайте {site_name}',
            'basket/order-mail.html',
            {'order': self.object},
            XendorSettings().get(u'E-mail администратора'))

        if self.object.mail:
            self.send_mail(
                'Новая покупка на сайте {site_name}',
                'basket/confirm-mail.html',
                {'order': self.object},
                self.object.mail)

        return super(OrderView, self).form_valid(form)


class AddToBasket(ContentTypeMixin, RefererRedirectWithMessage):
    """добавление одного товара в корзину"""

    action_message = u'Товар добавлен в корзину'

    def action(self):
        basket = self.request.session.get('basket', {})
        pk = self.kwargs['content_type_id'] + '-' + self.kwargs['object_id']
        try:
            basket[pk]['count'] += 1
        except KeyError:
            basket[pk] = {
                'count': 1,
                'content_type_id': self.kwargs['content_type_id'],
                'object_id': self.kwargs['object_id']
            }

        basket.update(price=_recalculate_basket_price(basket))
        self.request.session['basket'] = basket

    def get_redirect_url(self, *args, **kwargs):
        return super(AddToBasket, self).get_redirect_url(*args, **kwargs) + '#animate-basket'


class RemoveFromBasket(ContentTypeMixin, RefererRedirectWithMessage):
    """Удаление товара из корзины"""

    action_message = u'Товар удален из корзины'

    def action(self):
        basket = self.request.session.get('basket', {})
        pk = self.kwargs['content_type_id'] + '-' + self.kwargs['object_id']

        del basket[pk]

        basket.update(price=_recalculate_basket_price(basket))
        self.request.session['basket'] = basket


class RemoveOneFromBasket(ContentTypeMixin, RefererRedirectWithMessage):
    """Удаление товара из корзины"""

    action_message = u'Товар удален из корзины'

    def action(self):
        basket = self.request.session.get('basket', {})
        pk = self.kwargs['content_type_id'] + '-' + self.kwargs['object_id']

        if basket[pk]['count'] == 1:
            del basket[pk]
        else:
            basket[pk]['count'] -= 1

        basket.update(price=_recalculate_basket_price(basket))
        self.request.session['basket'] = basket


class AddToBasketJSON(ContentTypeMixin, JSONResponseMixin, TemplateView):
    """добавление одного товара в корзину"""

    def get_context_data(self, **kwargs):

        basket = self.request.session.get('basket', {})
        pk = self.kwargs['content_type_id'] + '-' + self.kwargs['object_id']
        try:
            basket[pk]['count'] += 1
        except KeyError:
            basket[pk] = {
                'count': 1,
                'content_type_id': self.kwargs['content_type_id'],
                'object_id': self.kwargs['object_id']
            }

        price = _recalculate_basket_price(basket)
        basket.update(price=price)
        self.request.session['basket'] = basket

        return {'price': _formater_1000(str(price)), 'count': basket[pk]['count']}


class RemoveFromBasketJSON(ContentTypeMixin, JSONResponseMixin, TemplateView):
    """Удаление товара из корзины"""

    action_message = u'Товар удален из корзины'

    def get_context_data(self, **kwargs):
        basket = self.request.session.get('basket', {})
        pk = self.kwargs['content_type_id'] + '-' + self.kwargs['object_id']

        del basket[pk]

        price = _recalculate_basket_price(basket)
        basket.update(price=price)
        self.request.session['basket'] = basket

        return {'price': _formater_1000(str(price)), 'count': 0}


class RemoveOneFromBasketJSON(ContentTypeMixin, JSONResponseMixin, TemplateView):
    """Удаление товара из корзины"""

    action_message = u'Товар удален из корзины'

    def get_context_data(self, **kwargs):
        basket = self.request.session.get('basket', {})
        pk = self.kwargs['content_type_id'] + '-' + self.kwargs['object_id']

        try:
            if basket[pk]['count'] == 1:
                del basket[pk]
                count = 0
            else:
                basket[pk]['count'] -= 1
                count = basket[pk]['count']
        except:
            pass


        price = _recalculate_basket_price(basket)
        basket.update(price=price)
        self.request.session['basket'] = basket

        return {'price': _formater_1000(str(price)), 'count': count}


class SetCountBasket(ContentTypeMixin, JSONResponseMixin, TemplateView):
    """Установка определенного количества товаров в корзине"""

    http_method_names = [u'get']

    template_name = ''

    def get_context_data(self, **kwargs):

        basket = self.request.session.get('basket', {})
        pk = self.kwargs['content_type_id'] + '-' + self.kwargs['object_id']
        count = int(self.request.GET.get('count', 1))

        try:
            basket[pk]['count'] = count
        except KeyError:
            basket[pk] = {
                'count': count,
                'content_type_id': self.kwargs['content_type_id'],
                'object_id': self.kwargs['object_id']
            }

        price = _recalculate_basket_price(basket)
        basket.update(price=price)
        self.request.session['basket'] = basket

        return {'price': _formater_1000(str(price))}


class GetDelivery(JSONResponseMixin, TemplateView):
    """Получения значения стоимости доставки"""

    http_method_names = [u'get']

    template_name = ''

    def get_context_data(self, **kwargs):

        basket = self.request.session.get('basket', {})

        price = float(basket.get('price'))
        delivery_price = 0
        payment_price = 0
        if self.request.GET.get('delivery'):
            delivery = get_object_or_404(Delivery, pk=self.request.GET.get('delivery'))
            delivery_price = float(delivery.price)

        if self.request.GET.get('payment'):
            payment = get_object_or_404(Payment, pk=self.request.GET.get('payment'))
            payment_price = float(payment.price)

        price = float(price) + float(delivery_price)
        price = price + (float(payment_price) * price/100)

        return {
            'price': _formater_1000(str(price)),
            'deliveryCost': delivery_price,
            'paymentCost': payment_price
        }

app/basket/templates/basket/confirm-mail.html
<h1>На сайте {{ site_name }} был оформлен заказ</h1>

Добрый день, {{ order.person }}!
--------------------------------------------------------
Спасибо за покупку в нашем интернет-магазине T-Sport
Наши менеджеры свяжутся с вами по координатам,
оставленным в форме заказа.

Подробности заказа № {{ order.pk }} от {{ order.created|date:"D d M Y" }}
--------------------------------------------------------
Контактное лицо: {{ order.person }}.
Телефон: {{ order.phone }}
Адрес и доп. инф: {{ order.address }}
Дата: {{ order.created }}
Доставка: {{ order.delivery }}
E-mail: {{ order.mail }}
Тип оплаты: {{ order.payment }}

Заказанные товары
-------------------------------------------------------
{% for item in order.ordereditem_set.all %}
    {{ item }} ({{ item.count }} шт. * {{ item.price }}) -- {{ item.get_total_price }}<br>
{% endfor %}
<br>
<br>
Итого: {{ order.price }}

-------------------------------------------------------
Стоимость заказа может измениться в одном из следующих случаев:
Доставка товара будет осуществляться в отдаленный район в соответствии с правилами доставки товара.
Отпускная цена изменена поставщиком, но пока не отредактирована на сайте нашими менеджерами.
Цена заказа фиксируется во время уточняющего звонка, который в ближайшее время поступит на Ваш телефон.
-------------------------------------------------------

Если у Вас возникнут вопросы, пожалуйста свяжитесь с нами по телефону горячей линии 8(343) 319-40-69

---------------------------------------------------------
C Уважением, Компания T-Sport г. Екатеринбург www.t-sport66.ru (343) 319-40-69

app/basket/templates/basket/order-mail.html
<h1>На сайте {{ site_name }} был оформлен заказ</h1>

<h2>Контактные данные:</h2>

<b>Персона:</b> {{ order.person }}<br />
<b>Телефон:</b> {{ order.phone }}<br />
<b>Почта:</b> {{ order.mail }}<br />
<b>Адрес:</b> {{ order.address }}<br />
<b>Комментарий:</b> {{ order.comment }}<br />
<b>Сумма заказа:</b> {{ order.price }}<br />

<h2>Данные заказа:</h2>
<pre>
{% for item in order.ordereditem_set.all %}
    {{ item }}<br />
{% endfor %}
</pre>

app/basket/templates/basket/order.html
{% extends 'base.html' %}
{% load xendor_tags basket_tags bootstrap3 promo_tags %}

{% block content %}
    <div class="modal fade" id="offerta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h1>Пользовательское соглашение</h1>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12 typography-content">
                            {% xendor_page '23' as offerta %}
                            {{ offerta.content|safe }}
                        </div>
                    </div>
                </div>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2>Товары в корзине</h2>

            {% if price %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Фото</th>
                            <th>Название</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th>Удалить</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in items %}
                            {% basket_url 'basket-remove' item.0 as basket_remove_url %}
                            <tr>
                                <td class="order-photo">
                                    <img src="{{ item.0.image|xthumbnail:'120;120;blank' }}" alt=""/>
                                </td>
                                <td>
                                    <h3><a href="{{ item.0.get_absolute_url }}">{{ item.0.name }}</a></h3>
                                </td>
                                <td>
                                    <input type="text" value="{{ item.1 }}" class="spinner" rel="{% basket_url_link 'basket-set-count' item.0 %}" disabled/>
                                </td>
                                <td class="order-price">
                                    {{ item.0.price|x1000 }} р.
                                </td>
                                <td class="order-del">
                                    <a href="{{ basket_remove_url }}"><span class="glyphicon glyphicon-remove-sign"></span></a>
                                </td>
                            </tr>
                        {% endfor %}

                    </tbody>
                    <tfoot>
                        <tr>
                            <th colspan="5" class="text-right order-total">
                                Итого: <span class="total">{{ price|x1000 }}</span> р.
                            </th>
                        </tr>
                    </tfoot>
                </table>

                <div class="gap-10"></div>
                <h2 id="full-form">Оформление заказа</h2>

                <form role="form" action="" method="post" id="basket-order-form" class="typography-content">
                    <div class="row">
                        <div class="col-md-7 col-lg-8">
                            {% csrf_token %}
                            {{ form.non_field_errors }}

                            <div class="form-group">
                                {{ form.phone.label_tag }}
                                {{ form.phone.errors }}
                                {{ form.phone }}
                            </div>

                            <div class="form-group">
                                {{ form.person.label_tag }}
                                {{ form.person.errors }}
                                {{ form.person }}
                            </div>

                            <div class="form-group">
                                {{ form.delivery.label_tag }}
                                {{ form.delivery.errors }}
                                {{ form.delivery }}
                                <div class="delivery-cost"></div>
                            </div>

                            <div class="form-group">
                                {{ form.payment.label_tag }}
                                {{ form.payment.errors }}
                                {{ form.payment }}
                                <div class="payment-cost"></div>
                            </div>

                            <div class="form-group">
                                {{ form.mail.label_tag }}
                                {{ form.mail.errors }}
                                {{ form.mail }}
                            </div>

                            <div class="form-group">
                                {{ form.address.label_tag }}
                                {{ form.address.errors }}
                                {{ form.address }}
                            </div>

                            <div class="form-group">
                                {{ form.comment.label_tag }}
                                {{ form.comment.errors }}
                                {{ form.comment }}
                            </div>
                              <p class=""><label>{{ form.eula }}
                                     Я прочитал(-а) и принимаю условия
                                </label>
                              <a href="#offerta" role="button" data-toggle="modal"> пользовательского соглашения</a>
                              </p>

                            <button type="submit" class="btn add-to-cart disabled">Оформить покупку</button>
                            <div class="gap-10"></div>
                        </div>
                        <div class="col-md-5 col-lg-4">
                            <div class="delivery-panel">
                                Ближайшая доставка через: <br/>
{#                                <span>6 д 13 ч 38 мин</span>#}
                                <span>{% countdown %}</span>
                            </div>
                            <div class="gap-10"></div>
                        </div>
                    </div>



{#                    <button type="submit" class="btn add-to-cart disabled">Оформить покупку</button>#}
                    <br class="clear"/>
{#                    <div class="gap-10"></div>#}
{#                    <blockquote>Если вам не трудно вы можете помочь нам улучшить качество нашей работы соощив дополнительные данные#}
{#                        <a href="#full-form" class="ajax show-full-form">Подробный заказ</a>#}
{#                    </blockquote>#}

{#full-form#}
                    <div class="">
{#                        <h2>Подробный заказ</h2>#}

                    </div>
                </form>

{#                <h2>Заказ </h2>#}

{#                <form role="form" action="" method="post">#}
{#                    {% csrf_token %}#}
{#                    {{ form.errors }}#}
{#                    {% bootstrap_form form %}#}
{##}
{#                  <div class="gap-10"></div>#}
{#                  <button type="submit" class="btn add-to-cart">Оформить покупку</button>#}
{#                </form>#}
            {% else %}
                <blockquote>Ваша корзина пуста</blockquote>
            {% endif %}
        </div>
    </div>

    <div class="gap-10"></div>

{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="application/javascript">
        $(document).ready(function(){

            $( ".spinner" ).spinner({
                icons: { down: "ui-icon-minusthick", up: "ui-icon-plusthick" },
                min: 1,
                stop: function( event, ui ) {
                    $.getJSON($(this).attr('rel'), {'count': $(this).val()}, function(data){
                        $('.total').html(data.price)
                        checkDelivery($('.delivery-calculation').val())
                        checkPayment($('.payment-calculation').val())
                    })

                }
            });

            $('.show-full-form').click(function(){
                $('.full-form').show()
            })

            $('#basket-order-form').submit(function(){
                if($('#id_eula:checked').length > 0){
                    return true;
                }
                return false;
            })

            if($('#id_eula:checked').length > 0){
                $('.add-to-cart').removeClass('disabled')
            }

            $('#id_eula').change(function(){
                if($('#id_eula:checked').length > 0){
                    $('.add-to-cart').removeClass('disabled')
                }else{
                    $('.add-to-cart').addClass('disabled')
                }
            })

            var checkDelivery = function(val){
                $.getJSON('{% url 'basket-get-delivery' %}', { delivery: val, payment: $('.payment-calculation').val() }, function(data) {

                    $('.delivery-cost').html('+ ' + data.deliveryCost + ' руб.')
                    $('.total').html(data.price)

                    if(data.deliveryCost == ''){
                        $('.delivery-cost').html('')
                    }
                })
            }

            var checkPayment = function(val){
                $.getJSON('{% url 'basket-get-delivery' %}', { payment: val, delivery: $('.delivery-calculation').val() }, function(data) {

                    $('.payment-cost').html('+ ' + data.paymentCost + '%')
                    $('.total').html(data.price)

                    if(data.paymentCost == ''){
                        $('.payment-cost').html('')
                    }
                })
            }

            $('.delivery-calculation').change(function(){
                checkDelivery($(this).val())
            })


            $('.payment-calculation').change(function(){
                checkPayment($(this).val())
            })

            checkDelivery($('.delivery-calculation').val())
            checkPayment($('.payment-calculation').val())

            if(window.location.href.split('#')[1] == 'full-form'){
                $('.full-form').show()
            }

            return true;
        });
    </script>
{% endblock %}

{% block basket-informer %}{% endblock %}

app/basket/templates/basket/success.html
{% extends 'base.html' %}

{% block content %}

    <h2>Заказ успешно оформлен</h2>
    <blockquote>
    В ближайшее время с вами свяжется наш менеджер для уточнения деталей заказа
    </blockquote>
{% endblock %}